//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.28 at 03:23:37 PM EDT 
//


package source;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}IncidentDelay"/>
 *         &lt;element ref="{}Description"/>
 *         &lt;element ref="{}Duration"/>
 *         &lt;element ref="{}IncidentPosition"/>
 *         &lt;element ref="{}Severity"/>
 *         &lt;element ref="{}IncidentStartTime"/>
 *         &lt;element ref="{}Visibility"/>
 *       &lt;/all>
 *       &lt;attribute ref="{}IncidentNum use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "IncidentModel")
public class IncidentModel {

    @XmlElement(name = "IncidentDelay", defaultValue = "0.2")
    protected float incidentDelay;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "Duration", defaultValue = "60.0")
    protected float duration;
    @XmlElement(name = "IncidentPosition", required = true)
    protected String incidentPosition;
    @XmlElement(name = "Severity", required = true, defaultValue = "Level 0")
    protected String severity;
    @XmlElement(name = "IncidentStartTime", defaultValue = "0")
    protected int incidentStartTime;
    @XmlElement(name = "Visibility", defaultValue = "50.0")
    protected float visibility;
    @XmlAttribute(name = "IncidentNum", required = true)
    protected int incidentNum;

    /**
     * Gets the value of the incidentDelay property.
     * 
     */
    public float getIncidentDelay() {
        return incidentDelay;
    }

    /**
     * Sets the value of the incidentDelay property.
     * 
     */
    public void setIncidentDelay(float value) {
        this.incidentDelay = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     */
    public float getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     */
    public void setDuration(float value) {
        this.duration = value;
    }

    /**
     * Gets the value of the incidentPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncidentPosition() {
        return incidentPosition;
    }

    /**
     * Sets the value of the incidentPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncidentPosition(String value) {
        this.incidentPosition = value;
    }

    /**
     * Gets the value of the severity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeverity() {
        return severity;
    }

    /**
     * Sets the value of the severity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeverity(String value) {
        this.severity = value;
    }

    /**
     * Gets the value of the incidentStartTime property.
     * 
     */
    public int getIncidentStartTime() {
        return incidentStartTime;
    }

    /**
     * Sets the value of the incidentStartTime property.
     * 
     */
    public void setIncidentStartTime(int value) {
        this.incidentStartTime = value;
    }

    /**
     * Gets the value of the visibility property.
     * 
     */
    public float getVisibility() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     */
    public void setVisibility(float value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the incidentNum property.
     * 
     */
    public int getIncidentNum() {
        return incidentNum;
    }

    /**
     * Sets the value of the incidentNum property.
     * 
     */
    public void setIncidentNum(int value) {
        this.incidentNum = value;
    }

}
