//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.28 at 03:23:37 PM EDT 
//


package source;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}Caption"/>
 *         &lt;element ref="{}MapDelay"/>
 *         &lt;element ref="{}Follow"/>
 *         &lt;element ref="{}Height"/>
 *         &lt;element ref="{}Width"/>
 *         &lt;element ref="{}StartPos"/>
 *         &lt;element ref="{}Zoom"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "MapModel")
public class MapModel {

    @XmlElement(name = "Caption", required = true, defaultValue = "GrooveNet Widget")
    protected String caption;
    @XmlElement(name = "MapDelay", defaultValue = "0.2")
    protected float mapDelay;
    @XmlElement(name = "Follow", required = true, defaultValue = "")
    protected String follow;
    @XmlElement(name = "Height", defaultValue = "373")
    protected int height;
    @XmlElement(name = "Width", defaultValue = "529")
    protected int width;
    @XmlElement(name = "StartPos", required = true, defaultValue = "0,0")
    protected String startPos;
    @XmlElement(name = "Zoom", defaultValue = "6")
    protected int zoom;

    /**
     * Gets the value of the caption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaption() {
        return caption;
    }

    /**
     * Sets the value of the caption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaption(String value) {
        this.caption = value;
    }

    /**
     * Gets the value of the mapDelay property.
     * 
     */
    public float getMapDelay() {
        return mapDelay;
    }

    /**
     * Sets the value of the mapDelay property.
     * 
     */
    public void setMapDelay(float value) {
        this.mapDelay = value;
    }

    /**
     * Gets the value of the follow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFollow() {
        return follow;
    }

    /**
     * Sets the value of the follow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFollow(String value) {
        this.follow = value;
    }

    /**
     * Gets the value of the height property.
     * 
     */
    public int getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     */
    public void setHeight(int value) {
        this.height = value;
    }

    /**
     * Gets the value of the width property.
     * 
     */
    public int getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     */
    public void setWidth(int value) {
        this.width = value;
    }

    /**
     * Gets the value of the startPos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartPos() {
        return startPos;
    }

    /**
     * Sets the value of the startPos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartPos(String value) {
        this.startPos = value;
    }

    /**
     * Gets the value of the zoom property.
     * 
     */
    public int getZoom() {
        return zoom;
    }

    /**
     * Sets the value of the zoom property.
     * 
     */
    public void setZoom(int value) {
        this.zoom = value;
    }

}
