//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.28 at 03:23:37 PM EDT 
//


package source;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the source package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RbxInterval_QNAME = new QName("", "RbxInterval");
    private final static QName _Caption_QNAME = new QName("", "Caption");
    private final static QName _RSUPosition_QNAME = new QName("", "RSUPosition");
    private final static QName _IncidentPosition_QNAME = new QName("", "IncidentPosition");
    private final static QName _MaxDistance_QNAME = new QName("", "MaxDistance");
    private final static QName _DetectRange_QNAME = new QName("", "DetectRange");
    private final static QName _ListDelay_QNAME = new QName("", "ListDelay");
    private final static QName _Log_QNAME = new QName("", "Log");
    private final static QName _Severity_QNAME = new QName("", "Severity");
    private final static QName _VehicleDelay_QNAME = new QName("", "VehicleDelay");
    private final static QName _Follow_QNAME = new QName("", "Follow");
    private final static QName _Duration_QNAME = new QName("", "Duration");
    private final static QName _StartAddress_QNAME = new QName("", "StartAddress");
    private final static QName _StartPos_QNAME = new QName("", "StartPos");
    private final static QName _Width_QNAME = new QName("", "Width");
    private final static QName _SimpleLinkModel_QNAME = new QName("", "SimpleLinkModel");
    private final static QName _GateWay_QNAME = new QName("", "GateWay");
    private final static QName _IncidentStartTime_QNAME = new QName("", "IncidentStartTime");
    private final static QName _Description_QNAME = new QName("", "Description");
    private final static QName _RSUDelay_QNAME = new QName("", "RSUDelay");
    private final static QName _Zoom_QNAME = new QName("", "Zoom");
    private final static QName _IncidentDelay_QNAME = new QName("", "IncidentDelay");
    private final static QName _RbxJitter_QNAME = new QName("", "RbxJitter");
    private final static QName _Height_QNAME = new QName("", "Height");
    private final static QName _MultiChannel_QNAME = new QName("", "MultiChannel");
    private final static QName _VehicleStartTime_QNAME = new QName("", "VehicleStartTime");
    private final static QName _MultiLane_QNAME = new QName("", "MultiLane");
    private final static QName _TrackSpeed_QNAME = new QName("", "TrackSpeed");
    private final static QName _MapDelay_QNAME = new QName("", "MapDelay");
    private final static QName _Visibility_QNAME = new QName("", "Visibility");
    private final static QName _Rbx_QNAME = new QName("", "Rbx");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: source
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CarList }
     * 
     */
    public CarList createCarList() {
        return new CarList();
    }

    /**
     * Create an instance of {@link IncidentModel }
     * 
     */
    public IncidentModel createIncidentModel() {
        return new IncidentModel();
    }

    /**
     * Create an instance of {@link MapModel }
     * 
     */
    public MapModel createMapModel() {
        return new MapModel();
    }

    /**
     * Create an instance of {@link RandomWalkModel }
     * 
     */
    public RandomWalkModel createRandomWalkModel() {
        return new RandomWalkModel();
    }

    /**
     * Create an instance of {@link ForwardThresh }
     * 
     */
    public ForwardThresh createForwardThresh() {
        return new ForwardThresh();
    }

    /**
     * Create an instance of {@link RSUModel }
     * 
     */
    public RSUModel createRSUModel() {
        return new RSUModel();
    }

    /**
     * Create an instance of {@link SimplePhysModel }
     * 
     */
    public SimplePhysModel createSimplePhysModel() {
        return new SimplePhysModel();
    }

    /**
     * Create an instance of {@link RoleModel }
     * 
     */
    public RoleModel createRoleModel() {
        return new RoleModel();
    }

    /**
     * Create an instance of {@link TrustUp }
     * 
     */
    public TrustUp createTrustUp() {
        return new TrustUp();
    }

    /**
     * Create an instance of {@link VehicleModel }
     * 
     */
    public VehicleModel createVehicleModel() {
        return new VehicleModel();
    }

    /**
     * Create an instance of {@link LieFreq }
     * 
     */
    public LieFreq createLieFreq() {
        return new LieFreq();
    }

    /**
     * Create an instance of {@link LieThresh }
     * 
     */
    public LieThresh createLieThresh() {
        return new LieThresh();
    }

    /**
     * Create an instance of {@link SimpleCommModel }
     * 
     */
    public SimpleCommModel createSimpleCommModel() {
        return new SimpleCommModel();
    }

    /**
     * Create an instance of {@link TrustLow }
     * 
     */
    public TrustLow createTrustLow() {
        return new TrustLow();
    }

    /**
     * Create an instance of {@link DetectThresh }
     * 
     */
    public DetectThresh createDetectThresh() {
        return new DetectThresh();
    }

    /**
     * Create an instance of {@link StreetSpeedModel }
     * 
     */
    public StreetSpeedModel createStreetSpeedModel() {
        return new StreetSpeedModel();
    }

    /**
     * Create an instance of {@link Simulation }
     * 
     */
    public Simulation createSimulation() {
        return new Simulation();
    }

    /**
     * Create an instance of {@link IncidentList }
     * 
     */
    public IncidentList createIncidentList() {
        return new IncidentList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RbxInterval", defaultValue = "1")
    public JAXBElement<Integer> createRbxInterval(Integer value) {
        return new JAXBElement<Integer>(_RbxInterval_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Caption", defaultValue = "GrooveNet Widget")
    public JAXBElement<String> createCaption(String value) {
        return new JAXBElement<String>(_Caption_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RSUPosition")
    public JAXBElement<String> createRSUPosition(String value) {
        return new JAXBElement<String>(_RSUPosition_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IncidentPosition")
    public JAXBElement<String> createIncidentPosition(String value) {
        return new JAXBElement<String>(_IncidentPosition_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MaxDistance", defaultValue = "200.0")
    public JAXBElement<Float> createMaxDistance(Float value) {
        return new JAXBElement<Float>(_MaxDistance_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DetectRange")
    public JAXBElement<Float> createDetectRange(Float value) {
        return new JAXBElement<Float>(_DetectRange_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ListDelay", defaultValue = "0.2")
    public JAXBElement<Float> createListDelay(Float value) {
        return new JAXBElement<Float>(_ListDelay_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Log", defaultValue = "NO")
    public JAXBElement<String> createLog(String value) {
        return new JAXBElement<String>(_Log_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Severity", defaultValue = "Level 0")
    public JAXBElement<String> createSeverity(String value) {
        return new JAXBElement<String>(_Severity_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VehicleDelay", defaultValue = "0.2")
    public JAXBElement<Float> createVehicleDelay(Float value) {
        return new JAXBElement<Float>(_VehicleDelay_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Follow", defaultValue = "")
    public JAXBElement<String> createFollow(String value) {
        return new JAXBElement<String>(_Follow_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Duration", defaultValue = "60.0")
    public JAXBElement<Float> createDuration(Float value) {
        return new JAXBElement<Float>(_Duration_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StartAddress")
    public JAXBElement<String> createStartAddress(String value) {
        return new JAXBElement<String>(_StartAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StartPos", defaultValue = "0,0")
    public JAXBElement<String> createStartPos(String value) {
        return new JAXBElement<String>(_StartPos_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Width", defaultValue = "529")
    public JAXBElement<Integer> createWidth(Integer value) {
        return new JAXBElement<Integer>(_Width_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SimpleLinkModel")
    public JAXBElement<String> createSimpleLinkModel(String value) {
        return new JAXBElement<String>(_SimpleLinkModel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GateWay", defaultValue = "NO")
    public JAXBElement<String> createGateWay(String value) {
        return new JAXBElement<String>(_GateWay_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IncidentStartTime", defaultValue = "0")
    public JAXBElement<Integer> createIncidentStartTime(Integer value) {
        return new JAXBElement<Integer>(_IncidentStartTime_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RSUDelay", defaultValue = "0.2")
    public JAXBElement<Float> createRSUDelay(Float value) {
        return new JAXBElement<Float>(_RSUDelay_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Zoom", defaultValue = "6")
    public JAXBElement<Integer> createZoom(Integer value) {
        return new JAXBElement<Integer>(_Zoom_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IncidentDelay", defaultValue = "0.2")
    public JAXBElement<Float> createIncidentDelay(Float value) {
        return new JAXBElement<Float>(_IncidentDelay_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RbxJitter", defaultValue = "YES")
    public JAXBElement<String> createRbxJitter(String value) {
        return new JAXBElement<String>(_RbxJitter_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Height", defaultValue = "373")
    public JAXBElement<Integer> createHeight(Integer value) {
        return new JAXBElement<Integer>(_Height_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MultiChannel", defaultValue = "NO")
    public JAXBElement<String> createMultiChannel(String value) {
        return new JAXBElement<String>(_MultiChannel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VehicleStartTime", defaultValue = "0")
    public JAXBElement<Float> createVehicleStartTime(Float value) {
        return new JAXBElement<Float>(_VehicleStartTime_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MultiLane", defaultValue = "NO")
    public JAXBElement<String> createMultiLane(String value) {
        return new JAXBElement<String>(_MultiLane_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TrackSpeed", defaultValue = "NO")
    public JAXBElement<String> createTrackSpeed(String value) {
        return new JAXBElement<String>(_TrackSpeed_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MapDelay", defaultValue = "0.2")
    public JAXBElement<Float> createMapDelay(Float value) {
        return new JAXBElement<Float>(_MapDelay_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Visibility", defaultValue = "50.0")
    public JAXBElement<Float> createVisibility(Float value) {
        return new JAXBElement<Float>(_Visibility_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Rbx", defaultValue = "YES")
    public JAXBElement<String> createRbx(String value) {
        return new JAXBElement<String>(_Rbx_QNAME, String.class, null, value);
    }

}
