//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.28 at 03:23:37 PM EDT 
//


package source;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}DetectThresh"/>
 *         &lt;element ref="{}ForwardThresh"/>
 *         &lt;element ref="{}LieFreq"/>
 *         &lt;element ref="{}LieThresh"/>
 *         &lt;element ref="{}TrustLow"/>
 *         &lt;element ref="{}TrustUp"/>
 *       &lt;/all>
 *       &lt;attribute ref="{}RoleType"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "RoleModel")
public class RoleModel {

    @XmlElement(name = "DetectThresh", required = true)
    protected DetectThresh detectThresh;
    @XmlElement(name = "ForwardThresh", required = true)
    protected ForwardThresh forwardThresh;
    @XmlElement(name = "LieFreq", required = true)
    protected LieFreq lieFreq;
    @XmlElement(name = "LieThresh", required = true)
    protected LieThresh lieThresh;
    @XmlElement(name = "TrustLow", required = true)
    protected TrustLow trustLow;
    @XmlElement(name = "TrustUp", required = true)
    protected TrustUp trustUp;
    @XmlAttribute(name = "RoleType")
    protected String roleType;

    /**
     * Gets the value of the detectThresh property.
     * 
     * @return
     *     possible object is
     *     {@link DetectThresh }
     *     
     */
    public DetectThresh getDetectThresh() {
        return detectThresh;
    }

    /**
     * Sets the value of the detectThresh property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetectThresh }
     *     
     */
    public void setDetectThresh(DetectThresh value) {
        this.detectThresh = value;
    }

    /**
     * Gets the value of the forwardThresh property.
     * 
     * @return
     *     possible object is
     *     {@link ForwardThresh }
     *     
     */
    public ForwardThresh getForwardThresh() {
        return forwardThresh;
    }

    /**
     * Sets the value of the forwardThresh property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForwardThresh }
     *     
     */
    public void setForwardThresh(ForwardThresh value) {
        this.forwardThresh = value;
    }

    /**
     * Gets the value of the lieFreq property.
     * 
     * @return
     *     possible object is
     *     {@link LieFreq }
     *     
     */
    public LieFreq getLieFreq() {
        return lieFreq;
    }

    /**
     * Sets the value of the lieFreq property.
     * 
     * @param value
     *     allowed object is
     *     {@link LieFreq }
     *     
     */
    public void setLieFreq(LieFreq value) {
        this.lieFreq = value;
    }

    /**
     * Gets the value of the lieThresh property.
     * 
     * @return
     *     possible object is
     *     {@link LieThresh }
     *     
     */
    public LieThresh getLieThresh() {
        return lieThresh;
    }

    /**
     * Sets the value of the lieThresh property.
     * 
     * @param value
     *     allowed object is
     *     {@link LieThresh }
     *     
     */
    public void setLieThresh(LieThresh value) {
        this.lieThresh = value;
    }

    /**
     * Gets the value of the trustLow property.
     * 
     * @return
     *     possible object is
     *     {@link TrustLow }
     *     
     */
    public TrustLow getTrustLow() {
        return trustLow;
    }

    /**
     * Sets the value of the trustLow property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrustLow }
     *     
     */
    public void setTrustLow(TrustLow value) {
        this.trustLow = value;
    }

    /**
     * Gets the value of the trustUp property.
     * 
     * @return
     *     possible object is
     *     {@link TrustUp }
     *     
     */
    public TrustUp getTrustUp() {
        return trustUp;
    }

    /**
     * Sets the value of the trustUp property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrustUp }
     *     
     */
    public void setTrustUp(TrustUp value) {
        this.trustUp = value;
    }

    /**
     * Gets the value of the roleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * Sets the value of the roleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoleType(String value) {
        this.roleType = value;
    }

}
