//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.28 at 03:23:37 PM EDT 
//


package source;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}RSUDelay"/>
 *         &lt;element ref="{}RSUPosition"/>
 *         &lt;element ref="{}SimpleCommModel"/>
 *         &lt;element ref="{}SimpleLinkModel"/>
 *         &lt;element ref="{}SimplePhysModel"/>
 *       &lt;/all>
 *       &lt;attribute ref="{}RSUNum use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "RSUModel")
public class RSUModel {

    @XmlElement(name = "RSUDelay", defaultValue = "0.2")
    protected float rsuDelay;
    @XmlElement(name = "RSUPosition", required = true)
    protected String rsuPosition;
    @XmlElement(name = "SimpleCommModel", required = true)
    protected SimpleCommModel simpleCommModel;
    @XmlElement(name = "SimpleLinkModel", required = true)
    protected String simpleLinkModel;
    @XmlElement(name = "SimplePhysModel", required = true)
    protected SimplePhysModel simplePhysModel;
    @XmlAttribute(name = "RSUNum", required = true)
    protected int rsuNum;

    /**
     * Gets the value of the rsuDelay property.
     * 
     */
    public float getRSUDelay() {
        return rsuDelay;
    }

    /**
     * Sets the value of the rsuDelay property.
     * 
     */
    public void setRSUDelay(float value) {
        this.rsuDelay = value;
    }

    /**
     * Gets the value of the rsuPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRSUPosition() {
        return rsuPosition;
    }

    /**
     * Sets the value of the rsuPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRSUPosition(String value) {
        this.rsuPosition = value;
    }

    /**
     * Gets the value of the simpleCommModel property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleCommModel }
     *     
     */
    public SimpleCommModel getSimpleCommModel() {
        return simpleCommModel;
    }

    /**
     * Sets the value of the simpleCommModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleCommModel }
     *     
     */
    public void setSimpleCommModel(SimpleCommModel value) {
        this.simpleCommModel = value;
    }

    /**
     * Gets the value of the simpleLinkModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimpleLinkModel() {
        return simpleLinkModel;
    }

    /**
     * Sets the value of the simpleLinkModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimpleLinkModel(String value) {
        this.simpleLinkModel = value;
    }

    /**
     * Gets the value of the simplePhysModel property.
     * 
     * @return
     *     possible object is
     *     {@link SimplePhysModel }
     *     
     */
    public SimplePhysModel getSimplePhysModel() {
        return simplePhysModel;
    }

    /**
     * Sets the value of the simplePhysModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimplePhysModel }
     *     
     */
    public void setSimplePhysModel(SimplePhysModel value) {
        this.simplePhysModel = value;
    }

    /**
     * Gets the value of the rsuNum property.
     * 
     */
    public int getRSUNum() {
        return rsuNum;
    }

    /**
     * Sets the value of the rsuNum property.
     * 
     */
    public void setRSUNum(int value) {
        this.rsuNum = value;
    }

}
