//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.28 at 03:23:37 PM EDT 
//


package source;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}GateWay"/>
 *         &lt;element ref="{}RbxJitter"/>
 *         &lt;element ref="{}Rbx"/>
 *         &lt;element ref="{}RbxInterval"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "SimpleCommModel")
public class SimpleCommModel {

    @XmlElement(name = "GateWay", required = true, defaultValue = "NO")
    protected String gateWay;
    @XmlElement(name = "RbxJitter", required = true, defaultValue = "YES")
    protected String rbxJitter;
    @XmlElement(name = "Rbx", required = true, defaultValue = "YES")
    protected String rbx;
    @XmlElement(name = "RbxInterval", defaultValue = "1")
    protected int rbxInterval;

    /**
     * Gets the value of the gateWay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGateWay() {
        return gateWay;
    }

    /**
     * Sets the value of the gateWay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGateWay(String value) {
        this.gateWay = value;
    }

    /**
     * Gets the value of the rbxJitter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRbxJitter() {
        return rbxJitter;
    }

    /**
     * Sets the value of the rbxJitter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRbxJitter(String value) {
        this.rbxJitter = value;
    }

    /**
     * Gets the value of the rbx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRbx() {
        return rbx;
    }

    /**
     * Sets the value of the rbx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRbx(String value) {
        this.rbx = value;
    }

    /**
     * Gets the value of the rbxInterval property.
     * 
     */
    public int getRbxInterval() {
        return rbxInterval;
    }

    /**
     * Sets the value of the rbxInterval property.
     * 
     */
    public void setRbxInterval(int value) {
        this.rbxInterval = value;
    }

}
