//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.28 at 03:23:37 PM EDT 
//


package source;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}VehicleModel" maxOccurs="unbounded"/>
 *         &lt;element ref="{}RSUModel" maxOccurs="unbounded"/>
 *         &lt;element ref="{}IncidentModel" maxOccurs="unbounded"/>
 *         &lt;element ref="{}MapModel"/>
 *         &lt;element ref="{}CarList"/>
 *         &lt;element ref="{}IncidentList"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{}Project"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vehicleModel",
    "rsuModel",
    "incidentModel",
    "mapModel",
    "carList",
    "incidentList"
})
@XmlRootElement(name = "Simulation")
public class Simulation {

    @XmlElement(name = "VehicleModel", required = true)
    protected List<VehicleModel> vehicleModel;
    @XmlElement(name = "RSUModel", required = true)
    protected List<RSUModel> rsuModel;
    @XmlElement(name = "IncidentModel", required = true)
    protected List<IncidentModel> incidentModel;
    @XmlElement(name = "MapModel", required = true)
    protected MapModel mapModel;
    @XmlElement(name = "CarList", required = true)
    protected CarList carList;
    @XmlElement(name = "IncidentList", required = true)
    protected IncidentList incidentList;
    @XmlAttribute(name = "Project")
    protected String project;

    /**
     * Gets the value of the vehicleModel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vehicleModel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVehicleModel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VehicleModel }
     * 
     * 
     */
    public List<VehicleModel> getVehicleModel() {
        if (vehicleModel == null) {
            vehicleModel = new ArrayList<VehicleModel>();
        }
        return this.vehicleModel;
    }

    /**
     * Gets the value of the rsuModel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rsuModel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRSUModel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RSUModel }
     * 
     * 
     */
    public List<RSUModel> getRSUModel() {
        if (rsuModel == null) {
            rsuModel = new ArrayList<RSUModel>();
        }
        return this.rsuModel;
    }

    /**
     * Gets the value of the incidentModel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incidentModel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncidentModel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IncidentModel }
     * 
     * 
     */
    public List<IncidentModel> getIncidentModel() {
        if (incidentModel == null) {
            incidentModel = new ArrayList<IncidentModel>();
        }
        return this.incidentModel;
    }

    /**
     * Gets the value of the mapModel property.
     * 
     * @return
     *     possible object is
     *     {@link MapModel }
     *     
     */
    public MapModel getMapModel() {
        return mapModel;
    }

    /**
     * Sets the value of the mapModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link MapModel }
     *     
     */
    public void setMapModel(MapModel value) {
        this.mapModel = value;
    }

    /**
     * Gets the value of the carList property.
     * 
     * @return
     *     possible object is
     *     {@link CarList }
     *     
     */
    public CarList getCarList() {
        return carList;
    }

    /**
     * Sets the value of the carList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarList }
     *     
     */
    public void setCarList(CarList value) {
        this.carList = value;
    }

    /**
     * Gets the value of the incidentList property.
     * 
     * @return
     *     possible object is
     *     {@link IncidentList }
     *     
     */
    public IncidentList getIncidentList() {
        return incidentList;
    }

    /**
     * Sets the value of the incidentList property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncidentList }
     *     
     */
    public void setIncidentList(IncidentList value) {
        this.incidentList = value;
    }

    /**
     * Gets the value of the project property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProject() {
        return project;
    }

    /**
     * Sets the value of the project property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProject(String value) {
        this.project = value;
    }

}
